
server:
  address: 127.0.0.1
  port: ${port:9002}


##h2
#spring:
#  datasource:
#      url: jdbc:h2:file:~/.h2/testdbt;DB_CLOSE_ON_EXIT=FALSE
#      username: sa
#      password: sa
#      driverClassName:   org.h2.Driver
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update




#mysql
spring:
  devtools:
      restart:
        enabled: true
        additional-exclude:
          - "**/*.yml, **/*.xml"
          - src/main/resources/sql

  output:
    ansi:
      enabled: detect
  datasource:
      url: jdbc:mysql://localhost:3306/logistics?useUnicode=true&characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull
      username: admin
      password: 123456
      driverClassName:  com.mysql.jdbc.Driver
      tomcat:
            test-while-idle: true
            validation-query: SELECT 1
  jpa:
    properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
          naming:
            strategy: org.hibernate.cfg.ImprovedNamingStrategy
          ddl-auto: update
    show-sql: true

# Set the file size limit (default 1Mb). If you want to specify that files be
# unlimited set the multipart.maxFileSize property to -1.

  http:
    multipart:
      maxFileSize: 10MB
      # Set the total request size for a multipart/form-data (default 10Mb)
      maxRequestSize: 30MB

mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
    defaultFetchSize: 100
    defaultStatementTimeout: 30

logging:
    level:
        com:
          spring:
            ibatis: DEBUG
        org:
            hibernate:
                SQL: DEBUG
                type:
                    descriptor:
                        sql:
                            BasicBinder: TRACE

cron:
  cron1: 0 * * * * MON-FRI
  cron2: 0 */2 * * * *

# JWT
jwt:
  tokenHeader: Authorization
  secret: bestskip
  expiration: 31536000

