
server:
  address: 127.0.0.1
  port: ${port:9002}

#;AUTO_SERVER=TRUE
#jdbc:h2:tcp://localhost/~/.h2/testdbt
spring:
  datasource:
      url: jdbc:h2:file:~/.h2/testdbt;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password: sa
      driverClassName:   org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


mybatis:
  configuration:
    mapUnderscoreToCamelCase: true


# JWT
jwt:
  tokenHeader: Authorization
  secret: bestskip
  expiration: 31536000