
server:
  address: 127.0.0.1
  port: ${port:9002}



##h2
#spring:
#  datasource:
#      url: jdbc:h2:file:~/.h2/testdbt;DB_CLOSE_ON_EXIT=FALSE
#      username: sa
#      password: sa
#      driverClassName:   org.h2.Driver
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update




#mysql
spring:
  output:
    ansi:
      enabled: detect
  datasource:
      url: jdbc:mysql://localhost:3306/logistics?useUnicode=true&characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull
      username: admin
      password: 123456
      driverClassName:  com.mysql.jdbc.Driver
      tomcat:
            test-while-idle: true
            validation-query: SELECT 1
  jpa:
    properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
          naming:
            strategy: org.hibernate.cfg.ImprovedNamingStrategy
          ddl-auto: update
    show-sql: true


mybatis:
  configuration:
    mapUnderscoreToCamelCase: true


# JWT
jwt:
  tokenHeader: Authorization
  secret: bestskip
  expiration: 31536000